[build]
  command = "npm run build"
  publish = "dist"

# Redirección para asegurarnos de que el enrutamiento del lado del cliente funcione
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Configuración actualizada de headers para seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Actualizado para permitir la URL de Render
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://quickgasoline.onrender.com; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"
