# Configuración de Netlify para QuickGasoline

[build]
  # Directorio que contiene los archivos estáticos a desplegar
  publish = "public"
  # Comando de build (no se necesita realmente)
  command = "echo 'No build step required for static HTML/JS/CSS files'"

# Redirecciones para SPA (aplicación de página única)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Encabezados de seguridad
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Configuración CSP actualizada para permitir conexiones a Render
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://quickgasoline.onrender.com; font-src 'self'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"

# Redirecciones para rutas específicas
[[redirects]]
  from = "/api/*"
  to = "https://quickgasoline.onrender.com/api/:splat"
  status = 200
  force = true
