# Configuración de Netlify para QuickGasoline

[build]
  # Directorio que contiene los archivos estáticos a desplegar
  publish = "public"
  # Comando de build (no se necesita realmente)
  command = "echo 'No build step required for static HTML/JS/CSS files'"

# Redirecciones para SPA (aplicación de página única)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Encabezados de seguridad
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://quickgasoline.onrender.com; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
